---
- name: Update ssh keys
  hosts: all

  tasks:
  - name: get keys
    ansible.builtin.set_fact:
      keys: "{{ keys|default([]) + [ lookup('file', item) ] }}"
    with_fileglob: 
      - "{{ ssh_key_folder }}/*.pub"
  - name: Set ssh keys
    ansible.posix.authorized_key:
      exclusive: true
      key: "{{ keys | join(newline) }}"
      manage_dir: false
      state: present
      user: {{ deploy_user }}
    vars: 
      - newline: "\n"
