---
- name: Create minio data directories
  hosts: leader
  become: true
  tasks:
    - file:
        group: "{{ deploy_group }}"
        owner: "{{ deploy_user }}"
        path: "{{ item }}"
        state: directory
        recurse: true
      with_items:
        - "{{ deploy_dir }}/minio"
        - "{{ deploy_dir }}/minio/data"
  tags:
    - minio
  when:
    - minio_enabled
