---
- name: Create necessary portainer directories on the NFS server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        group: "nogroup"
        owner: "nobody"
        path: "/mnt/nfs/{{ item }}"
        state: directory
        recurse: true
      with_items:
        - "portainer"


- name: Deploy Portainer with NFS Volume
  hosts: leader
  become: true

  tasks:
    - name: Deploy Portainer
      ansible.builtin.import_role:
        name: dzangolab.ansible.docker_portainer # Need to be updated, or modified to use "test-nfs-server-portainer" branch from ansible
      vars:
        nfs__ip: "{{ nfs_server_ip }}"
        portainer__use_nfs: "{{ use_nfs_server }}"
