- name: Create required traefik directories and files on the NFS server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        group: "nogroup"
        owner: "nobody"
        path: "/mnt/nfs/{{ item }}"
        state: directory
        recurse: true
      with_items:
        - "traefik/acme"
        - "traefik/log"
    - name: Create an empty acme.json
      file:
        path: "/mnt/nfs/traefik/acme/acme.json"
        state: touch
        owner: "nobody"
        group: "nogroup"
        mode: "0600"
  when:
    - nfs