---
- name: Setup docker swarm
  hosts: all
  tasks:
    - name: install python docker module
      ansible.builtin.pip:
        name: docker

    - name: Fetch IP of the droplet
      uri:
        url: http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address
        return_content: yes
      register: metadata_response

    - name: Set IP as a fact
      set_fact:
        private_ip: "{{ metadata_response.content }}"

    - name: Check/init Swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ private_ip }}"