---
- name: Get secrets
  hosts: traefik
  tasks:
    - shell: "aws secretsmanager get-secret-value --output text --query SecretString --secret-id {{ aws_secrets_id }}"
      delegate_to: 127.0.0.1
      register: secrets

- name: Compute traefik htpasswd
  hosts: traefik
  tasks:
    - shell: "htpasswd -bn admin \"{{ (secrets.stdout | from_json)[\"traefik-dashboard-password\"] }}\" | sed -e 's/\\$/\\$\\$/g'"
      delegate_to: 127.0.0.1
      register: traefik_dashboard_basicauth_password

- name: Create necessary traefik directories on the NFS server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        group: "nogroup"
        owner: "nobody"
        path: "/mnt/nfs/{{ item }}"
        state: directory
        recurse: true
      with_items:
        - "traefik/acme"
        - "traefik/log"

- name: Create acme.json on the NFS server
  hosts: nfs_server
  become: yes
  tasks:
  - name: Create an empty acme.json
    file:
      path: "/mnt/nfs/traefik/acme/acme.json"
      state: touch
      owner: "nobody"
      group: "nogroup"
      mode: "0600"

- name: Deploy traefik
  hosts: traefik
  tasks:
    - name: Import traefik from dzangolab collection
      ansible.builtin.import_role:
        name: dzangolab.ansible.docker_traefik # Need to be updated, or modified to use "test-nfs-server-portainer" branch from ansible
      vars:
        traefik__nfs_ip: "{{ nfs_server_ip }}"
        traefik__use_nfs: "{{ use_nfs_server }}"
  vars:
    traefik__dashboard_basicauth_passwords: ["{{ traefik_dashboard_basicauth_password.stdout }}"]
