---
- name: Get secrets
  hosts: all
  tasks:
    - shell: "aws secretsmanager get-secret-value --output text --query SecretString --secret-id {{ aws_secrets_id }}"
      delegate_to: 127.0.0.1
      register: secrets

- name: Install aws-cli
  hosts: awscli
  roles:
    - role: dzangolab.awscli2
