aws_secrets_id: SECRET_ID

deploy_dir: /mnt/data
deploy_group: <%= username %>
deploy_user: <%= username %>

domain: <%= domain %>

mariadb_versions:
  - 11

network_private: private
network_public: public
nfs: <%= useNfs %>
nfs_server_ip: NFS_SERVER_PRIVATE_IP

postgres_versions:
  - 17
  - 16
  - 15

ssh_key_folder: ../../../../ssh-keys
ssh_keys:
 - SSH_KEY_1
 - SSH_KEY_2
