---
- name: Create docker networks
  hosts: swarm_managers[0]
  tasks:
    - command: "docker network create -d overlay --attachable {{ item }}"
      ignore_errors: yes
      with_items:
        - "{{ network_private }}"
        - "{{ network_traefik }}"
  tags:
    - docker-networks

- name: Label nodes
  hosts: all
  tasks:
    - name: Get node id
      command: "docker info -f {% raw %}'{{.Swarm.NodeID}}'{% endraw %}"
      register: node_id
    - name: label_node
      command: "docker node update --label-add {{ item }}=true {{ node_id.stdout }}"
      ignore_errors: yes
      with_items: "{{ hostvars[inventory_hostname].labels }}"
  tags:
    - docker-labels

- name: Prune system daily
  hosts: managers[0]
  become: true
  roles:
    - role: victy.ansible-systemd-timers
  vars:
    timers:
      dockerPrune:
        timer_command: /usr/bin/docker system prune -a -f --volumes
        timer_OnCalendar: "*-*-* 00:13:25"
  tags:
    - docker-cron
