---
- name: Create required portainer directories on the NFS server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        group: "nobody"
        owner: "nobody"
        path: "{{ portainer_deploy_dir }}/data"
        state: directory
        recurse: true
      when:
        - "{{ portainer_nfs }}"

- name: Deploy Portainer
  hosts: portainer
  become: true
  tasks:
    - name: Deploy Portainer
      ansible.builtin.import_role:
        name: dzangolab.ansible.docker_portainer
