---
- name: Create required traefik directories and files on the NFS server
  hosts: nfs_server
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        group: "nobody"
        owner: "nobody"
        path: "{{ traefik_deploy_dir }}/{{ item }}"
        state: directory
        recurse: true
      with_items:
        - "acme"
        - "log"
      when:
        - nfs

    - name: Create an empty acme.json
      file:
        path: "{{ traefik_deploy_dir }}/acme/acme.json"
        state: touch
        owner: "nobody"
        group: "nobody"
        mode: "0600"
      when:
        - nfs

- name: Deploy traefik
  hosts: traefik
  tasks:
    - name: Get secrets
      shell: "aws secretsmanager get-secret-value --output text --query SecretString --secret-id {{ aws_secrets_id }}"
      delegate_to: 127.0.0.1
      register: secrets
    - name: Compute traefik htpasswd
      shell: "htpasswd -bn admin \"{{ (secrets.stdout | from_json)[\"traefik-dashboard-password\"] }}\" | sed -e 's/\\$/\\$\\$/g'"
      delegate_to: 127.0.0.1
      register: traefik_dashboard_basicauth_password
    - name: Deploy traefik
      ansible.builtin.import_role:
        name: dzangolab.ansible.docker_traefik
      vars:
        traefik__dashboard_basicauth_passwords: ["{{ traefik_dashboard_basicauth_password.stdout }}"]
