traefik__acme_email: EMAIL
traefik__deploy_dir: "{{ deploy_dir }}/traefik"
traefik__deploy_group: "{{ deploy_group }}"
traefik__deploy_user: "{{ deploy_user }}"
traefik__domain: "traefik.{{ domain }}"
traefik__image: "traefik:v3.3.6"
traefik__label: "traefik"
traefik__network: "{{ network_public }}"
traefik__state: "started"
