traefik__acme_email: EMAIL
traefik__deploy_dir: "{{ deploy_dir }}/traefik"
traefik__deploy_group: "{{ deploy_group }}"
traefik__deploy_user: "{{ deploy_user }}"
traefik__domain: "traefik.{{ domain }}"
traefik__network: "{{ network_public }}"
traefik__nfs_ip: "{{ nfs_server_ip }}"
traefik__state: "started"
traefik__use_nfs: "{{ nfs }}"

